### PR TITLE
Support Extending Filetypes

### PR DESCRIPTION
**Pull request by saadparwaiz1**

### CODE REVIEW

**Comment by lambtho12** [comment]
Does not quite work.
Assuming I extend the markdown snippets so I can use them with vimwiki I have now the following:

In markdown: each snippet appears twice in nvim-cmp
In vimwiki:
- the markdown snippets appears twice 
-  vimwiki only snippets appears once.
-  when I select a snippet in cmp menu (any snippet), I have the following error
```
E5108: Error executing lua .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:774: Vi
m:E492: Not an editor command: VimtexEventInitPost call vimtex#syntax#core#init_post()
```
Then cmp seems to be completely broken and won't work at all, even in other buffers....

**Comment by L3MON4D3** [comment]
Ouh, probably because the results are loaded from cache, which just uses the raw filetype from params. `params.context.filetype` is just `vim.bo.filetype`(or at least in the same format, ie. `ft1.optionalft2.maybeevenft3`), yes?

**Comment by lambtho12** [comment]
I have no clue what you are talking about... :sweat_smile: 
Could you tell me what should I type to provide you with the relevant info?

**Comment by L3MON4D3** [comment]
That was more of an @saadparwaiz1, an idea where the error comes from. I would've  commented on the code directly but github doesn't want me to I guess :D

**Comment by saadparwaiz1** [comment]
> Ouh, probably because the results are loaded from cache, which just uses the raw filetype from params. `params.context.filetype` is just `vim.bo.filetype`(or at least in the same format, ie. `ft1.optionalft2.maybeevenft3`), yes?

Yeah `params.context.filetype` is just `vim.bo.filetype` but I doubt the markdown snippets apperaring twice is because of that?

**Comment by L3MON4D3** [comment]
No idea, it just struck me as probably not working correctly

**Comment by saadparwaiz1** [comment]
@lambtho12 can you share your config and I'll try to have a look at what's causing the issue?

**Comment by lambtho12** [comment]
My neovim config is a mess. I am still in the middle of rebuilding everything from scratch using lua.
Do you want all of it or only some parts?

**Comment by saadparwaiz1** [comment]
> My neovim config is a mess. I am still in the middle of rebuilding everything from scratch using lua.
> Do you want all of it or only some parts?

only the luasnip parts should work? if you can create a minimial config to reproduce the error that'll be great

**Comment by lambtho12** [comment]
So... I removed all my plugins and reinstalled them, and now there is no more error. I do not know what was the issue, but it seems to be fixed.

I also found why the entries were duplicated in the cmp menu... I had
```
require("luasnip/loaders/from_vscode").load({include = {"markdown"}})
require("luasnip").filetype_extend("vimwiki", {"markdown"})
require("luasnip/loaders/from_vscode").lazy_load()
```
when I deleted the first line, there were no duplicates anymore...

Thank you very much for your time

**Comment by saadparwaiz1** [comment]
Aye no worries. I'll merge this pull request now. let me know if there are any more issues

**Pull request merged**
