### PR TITLE
Use new luasnip-functions for expansion.

### PR DESCRIPTION
**Pull request by L3MON4D3**
Hi, I'm updating the expand-process of luasnip to allow for more functionality, these are the changes required on `cmp_luasnip`s side :)
Requires the `refactor_expand`-branch to be merged into luasnip.

### CODE REVIEW

**Comment by saadparwaiz1** [comment]
Perfect :) will merge once that branch has been merged!

**Comment by L3MON4D3** [comment]
When do you have some time to merge? We should merge simultaneously because expansion will be a bit broken if only one of the patches is present.

**Comment by saadparwaiz1** [comment]
@L3MON4D3 I'm free all day today. let me know what time works best for you?

**Comment by L3MON4D3** [comment]
Right now? :D

**Comment by saadparwaiz1** [comment]
sounds good to me

**Comment by L3MON4D3** [comment]
Merged!

**Comment by L3MON4D3** [comment]
Clean👌👌

**Comment by saadparwaiz1** [comment]
Merged here as well

**Comment by L3MON4D3** [comment]
Very nice, that should keep conflicts to a minimum👍

**Pull request merged**
