### PR TITLE
feat(autosnippets): Show autosnippets

### PR DESCRIPTION
**Pull request by saadparwaiz1**

### CODE REVIEW

**Review by wuilliam321 — COMMENTED** [review]
As a general review, there are missing file format. Maybe you can consider automate that xD.

**Comment by atticus-sullivan** [comment]
> @mathjiajia i don't use autosnippets so someone would have to test the pr :)

Ok this PR has been a while. Any specific things to test, or just check if autosnippets are shown (and nothing crashes)?

**Comment by saadparwaiz1** [comment]
> > @mathjiajia i don't use autosnippets so someone would have to test the pr :)
> 
> 
> 
> Ok this PR has been a while. Any specific things to test, or just check if autosnippets are shown (and nothing crashes)?

Mostly just testing that it works. I don't use autosnippets so haven't tested it out.

**Comment by atticus-sullivan** [comment]
:+1: Would you rebase this onto the master branch (right now changes like `Use new luasnip-functions to expand` are missing to be compatible to the current version of luasnip I guess) before.
(I can do this as well, but I'm not that familiar with the codebase of cmp_luasnip yet. So it's your call, if it's you or me)

**Comment by saadparwaiz1** [comment]
> :+1: Would you rebase this onto the master branch (right now changes like `Use new luasnip-functions to expand` are missing to be compatible to the current version of luasnip I guess) before.
> 
> (I can do this as well, but I'm not that familiar with the codebase of cmp_luasnip yet. So it's your call, if it's you or me)

Happy for you to take over the PR :)

**Comment by atticus-sullivan** [comment]
Alright. Gonna take some time though. Any chance to really take over the PR, or would I just create a new one?

**Comment by saadparwaiz1** [comment]
Whatever you prefer. If you don't get to it. I can do a refactor and clean things up in a few weeks time

**Comment by atticus-sullivan** [comment]
> As a general review, there are missing file format. Maybe you can consider automate that xD.

What do you mean by that @wuilliam321?

**Comment by wuilliam321** [comment]
> > As a general review, there are missing file format. Maybe you can consider automate that xD.
> 
> What do you mean by that @wuilliam321?

I think it's solved now, there were bad indentations and bad formatting, but it seems to be good now.

**Comment by saadparwaiz1** [comment]
I'll close this pull request as the other one got merged :D

**Pull request closed without merging**
